name: Latest blog post

on: 
  repository_dispatch: 
    types: [special_repository]
  workflow_dispatch:
  workflow_call:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "git config"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: gautamkrishnar/blog-post-workflow@eba05ad46e6bac02165b77289978caf47699a41f # v1.9.3
        with:
          feed_list: "https://shenxianpeng.github.io/en/index.xml"
          max_post_count: 10
          date_format: mmm d, yyyy
